// Copyright 2023 hanmajid (Muhammad Farhan Majid)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import 'package:flutter/widgets.dart';

/// Class containing Bold icons.
///
/// This font was generated by FlutterIcon.com.
class BoldIcons {
  /// No need for constructor. All properties are static.
  BoldIcons._();

  /// Bold icons family name.
  static const _kFontFam = 'BoldIcons';

  /// Bold icons package name.
  static const String? _kFontPkg = 'bold_icons';

  /// Icon data for 'adjust' glyph.
  static const IconData adjust =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'align_center' glyph.
  static const IconData align_center =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'align_justify' glyph.
  static const IconData align_justify =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'align_left' glyph.
  static const IconData align_left =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'align_right' glyph.
  static const IconData align_right =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'angle_double_right' glyph.
  static const IconData angle_double_right =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'angle_down' glyph.
  static const IconData angle_down =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'angle_double_left' glyph.
  static const IconData angle_double_left =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'angle_up' glyph.
  static const IconData angle_up =
      IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'angle_right' glyph.
  static const IconData angle_right =
      IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'apple_filled' glyph.
  static const IconData apple_filled =
      IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'archive_filled' glyph.
  static const IconData archive_filled =
      IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'apple_outline' glyph.
  static const IconData apple_outline =
      IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_left' glyph.
  static const IconData arrow_left =
      IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'angle_left' glyph.
  static const IconData angle_left =
      IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'archive_outline' glyph.
  static const IconData archive_outline =
      IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_down' glyph.
  static const IconData arrow_down =
      IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'ban_outline' glyph.
  static const IconData ban_outline =
      IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bandaid_filled' glyph.
  static const IconData bandaid_filled =
      IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_up' glyph.
  static const IconData arrow_up =
      IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'battery_low' glyph.
  static const IconData battery_low =
      IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'beach' glyph.
  static const IconData beach =
      IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'arrow_right' glyph.
  static const IconData arrow_right =
      IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'ban_filled' glyph.
  static const IconData ban_filled =
      IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bandaid_outline' glyph.
  static const IconData bandaid_outline =
      IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bookmark_filled' glyph.
  static const IconData bookmark_filled =
      IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bold' glyph.
  static const IconData bold =
      IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bell_filled' glyph.
  static const IconData bell_filled =
      IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'blood_pressure_outline' glyph.
  static const IconData blood_pressure_outline =
      IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bell_outline' glyph.
  static const IconData bell_outline =
      IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'blood_pressure_filled' glyph.
  static const IconData blood_pressure_filled =
      IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'battery_medium' glyph.
  static const IconData battery_medium =
      IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'battery_full' glyph.
  static const IconData battery_full =
      IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bookmark_outline' glyph.
  static const IconData bookmark_outline =
      IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'box_filled' glyph.
  static const IconData box_filled =
      IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'braille' glyph.
  static const IconData braille =
      IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'box_outline' glyph.
  static const IconData box_outline =
      IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'balance_filled' glyph.
  static const IconData balance_filled =
      IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'balance_outline' glyph.
  static const IconData balance_outline =
      IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bricks_outline' glyph.
  static const IconData bricks_outline =
      IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bridge' glyph.
  static const IconData bridge =
      IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'bricks_filled' glyph.
  static const IconData bricks_filled =
      IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar_filled' glyph.
  static const IconData calendar_filled =
      IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chat_outline' glyph.
  static const IconData chat_outline =
      IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'calendar_outline' glyph.
  static const IconData calendar_outline =
      IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check_circle_filled' glyph.
  static const IconData check_circle_filled =
      IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check_default' glyph.
  static const IconData check_default =
      IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'check_circle_outline' glyph.
  static const IconData check_circle_outline =
      IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'camera_outline' glyph.
  static const IconData camera_outline =
      IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'camera_filled' glyph.
  static const IconData camera_filled =
      IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'chat_filled' glyph.
  static const IconData chat_filled =
      IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clear_format' glyph.
  static const IconData clear_format =
      IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clock_outline' glyph.
  static const IconData clock_outline =
      IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cloud_outline' glyph.
  static const IconData cloud_outline =
      IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'contrast_active' glyph.
  static const IconData contrast_active =
      IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clock_arrow_outline' glyph.
  static const IconData clock_arrow_outline =
      IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'copy_filled' glyph.
  static const IconData copy_filled =
      IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clock_filled' glyph.
  static const IconData clock_filled =
      IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'code' glyph.
  static const IconData code =
      IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clip' glyph.
  static const IconData clip =
      IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cloud_filled' glyph.
  static const IconData cloud_filled =
      IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'clock_arrow_filled' glyph.
  static const IconData clock_arrow_filled =
      IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'contrast' glyph.
  static const IconData contrast =
      IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'continuous_medicine' glyph.
  static const IconData continuous_medicine =
      IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'copy_outline' glyph.
  static const IconData copy_outline =
      IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cross_filled_copy' glyph.
  static const IconData cross_filled_copy =
      IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cross_filled' glyph.
  static const IconData cross_filled =
      IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'credit_card_outline' glyph.
  static const IconData credit_card_outline =
      IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cutlery_outline' glyph.
  static const IconData cutlery_outline =
      IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cross_outline' glyph.
  static const IconData cross_outline =
      IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'data_check_filled' glyph.
  static const IconData data_check_filled =
      IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'credit_card_filled' glyph.
  static const IconData credit_card_filled =
      IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cutlery_filled' glyph.
  static const IconData cutlery_filled =
      IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'data_filled' glyph.
  static const IconData data_filled =
      IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'cross_outline_copy' glyph.
  static const IconData cross_outline_copy =
      IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'data_check_outlined' glyph.
  static const IconData data_check_outlined =
      IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'deaf' glyph.
  static const IconData deaf =
      IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dog_leashed' glyph.
  static const IconData dog_leashed =
      IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'desktop_outline' glyph.
  static const IconData desktop_outline =
      IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drop_filled' glyph.
  static const IconData drop_filled =
      IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dragdrop' glyph.
  static const IconData dragdrop =
      IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'drop_outline' glyph.
  static const IconData drop_outline =
      IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dots' glyph.
  static const IconData dots =
      IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dumbbell_filled' glyph.
  static const IconData dumbbell_filled =
      IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation_triangle_outline' glyph.
  static const IconData exclamation_triangle_outline =
      IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'email_filled' glyph.
  static const IconData email_filled =
      IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'email_outline' glyph.
  static const IconData email_outline =
      IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'download' glyph.
  static const IconData download =
      IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exchange' glyph.
  static const IconData exchange =
      IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'data_outline' glyph.
  static const IconData data_outline =
      IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye_hidden_filled' glyph.
  static const IconData eye_hidden_filled =
      IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'desktop_filled' glyph.
  static const IconData desktop_filled =
      IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation_default' glyph.
  static const IconData exclamation_default =
      IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'dumbbell_outline' glyph.
  static const IconData dumbbell_outline =
      IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'expand' glyph.
  static const IconData expand =
      IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye_hidden_outline' glyph.
  static const IconData eye_hidden_outline =
      IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye_outline' glyph.
  static const IconData eye_outline =
      IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'exclamation_triangle_filled' glyph.
  static const IconData exclamation_triangle_filled =
      IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'eye_filled' glyph.
  static const IconData eye_filled =
      IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'decrease_font' glyph.
  static const IconData decrease_font =
      IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'faucet_filled' glyph.
  static const IconData faucet_filled =
      IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'faucet_outline' glyph.
  static const IconData faucet_outline =
      IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_empty_filled' glyph.
  static const IconData file_empty_filled =
      IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_empty_outline' glyph.
  static const IconData file_empty_outline =
      IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_visualization_filled' glyph.
  static const IconData file_visualization_filled =
      IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_visualization_outline' glyph.
  static const IconData file_visualization_outline =
      IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_with_itens_filled' glyph.
  static const IconData file_with_itens_filled =
      IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'file_with_itens_outline' glyph.
  static const IconData file_with_itens_outline =
      IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'filter_filled' glyph.
  static const IconData filter_filled =
      IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'filter_outline' glyph.
  static const IconData filter_outline =
      IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder_filled' glyph.
  static const IconData folder_filled =
      IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'folder_outline' glyph.
  static const IconData folder_outline =
      IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'gear_filled' glyph.
  static const IconData gear_filled =
      IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'gear_outline' glyph.
  static const IconData gear_outline =
      IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'glucometer' glyph.
  static const IconData glucometer =
      IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'hamburguer_menu' glyph.
  static const IconData hamburguer_menu =
      IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart_filled' glyph.
  static const IconData heart_filled =
      IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart_outline' glyph.
  static const IconData heart_outline =
      IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart_rate_filled' glyph.
  static const IconData heart_rate_filled =
      IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'heart_rate_outline' glyph.
  static const IconData heart_rate_outline =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'hospital' glyph.
  static const IconData hospital =
      IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'house_filled' glyph.
  static const IconData house_filled =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'house_outline' glyph.
  static const IconData house_outline =
      IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image_filled' glyph.
  static const IconData image_filled =
      IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'image_outline' glyph.
  static const IconData image_outline =
      IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'imc_filled' glyph.
  static const IconData imc_filled =
      IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'increase_font' glyph.
  static const IconData increase_font =
      IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'info_circle_filled' glyph.
  static const IconData info_circle_filled =
      IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'info_circle_outline' glyph.
  static const IconData info_circle_outline =
      IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'info_default' glyph.
  static const IconData info_default =
      IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'italic' glyph.
  static const IconData italic =
      IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'key_filled' glyph.
  static const IconData key_filled =
      IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'key_outline' glyph.
  static const IconData key_outline =
      IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'leaf_filled' glyph.
  static const IconData leaf_filled =
      IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'leaf_outline' glyph.
  static const IconData leaf_outline =
      IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lightbulb_filled' glyph.
  static const IconData lightbulb_filled =
      IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lightbulb_outline' glyph.
  static const IconData lightbulb_outline =
      IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'link' glyph.
  static const IconData link =
      IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'list' glyph.
  static const IconData list =
      IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'loading' glyph.
  static const IconData loading =
      IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_close_filled' glyph.
  static const IconData lock_close_filled =
      IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_close_outline' glyph.
  static const IconData lock_close_outline =
      IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_open_filled' glyph.
  static const IconData lock_open_filled =
      IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lock_open_outline' glyph.
  static const IconData lock_open_outline =
      IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'lungs' glyph.
  static const IconData lungs =
      IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'map_filled' glyph.
  static const IconData map_filled =
      IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'map_marker_filled' glyph.
  static const IconData map_marker_filled =
      IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'map_marker_outline' glyph.
  static const IconData map_marker_outline =
      IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'map_outline' glyph.
  static const IconData map_outline =
      IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'medicine_bottle_filled' glyph.
  static const IconData medicine_bottle_filled =
      IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'medicine_bottle_outline' glyph.
  static const IconData medicine_bottle_outline =
      IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'medicine_exclamation' glyph.
  static const IconData medicine_exclamation =
      IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'microphone_filled' glyph.
  static const IconData microphone_filled =
      IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'microphone_outline' glyph.
  static const IconData microphone_outline =
      IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minimize' glyph.
  static const IconData minimize =
      IconData(0xe89a, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minus_circle_filled' glyph.
  static const IconData minus_circle_filled =
      IconData(0xe89b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'minus' glyph.
  static const IconData minus =
      IconData(0xe89c, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'module' glyph.
  static const IconData module =
      IconData(0xe89d, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mosquito' glyph.
  static const IconData mosquito =
      IconData(0xe89e, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mug_filled' glyph.
  static const IconData mug_filled =
      IconData(0xe89f, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'mug_outline' glyph.
  static const IconData mug_outline =
      IconData(0xe8a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'multiple_users_outline' glyph.
  static const IconData multiple_users_outline =
      IconData(0xe8a1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'multiple_users' glyph.
  static const IconData multiple_users =
      IconData(0xe8a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'needle_filled' glyph.
  static const IconData needle_filled =
      IconData(0xe8a3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'needle_outline' glyph.
  static const IconData needle_outline =
      IconData(0xe8a4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'no_data_filled' glyph.
  static const IconData no_data_filled =
      IconData(0xe8a5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'no_data_outline' glyph.
  static const IconData no_data_outline =
      IconData(0xe8a6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'nurse_view' glyph.
  static const IconData nurse_view =
      IconData(0xe8a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'nurse' glyph.
  static const IconData nurse =
      IconData(0xe8a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'o2_filled' glyph.
  static const IconData o2_filled =
      IconData(0xe8a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'open_door' glyph.
  static const IconData open_door =
      IconData(0xe8aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pause' glyph.
  static const IconData pause =
      IconData(0xe8ab, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pen_filled' glyph.
  static const IconData pen_filled =
      IconData(0xe8ac, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pen_outline' glyph.
  static const IconData pen_outline =
      IconData(0xe8ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pen_tool' glyph.
  static const IconData pen_tool =
      IconData(0xe8ae, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pessoa_com_deficiencia' glyph.
  static const IconData pessoa_com_deficiencia =
      IconData(0xe8af, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pet_filled' glyph.
  static const IconData pet_filled =
      IconData(0xe8b0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pet_outline' glyph.
  static const IconData pet_outline =
      IconData(0xe8b1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'phone_filled' glyph.
  static const IconData phone_filled =
      IconData(0xe8b2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'phone_outline' glyph.
  static const IconData phone_outline =
      IconData(0xe8b3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pill_filled' glyph.
  static const IconData pill_filled =
      IconData(0xe8b4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pill_outline' glyph.
  static const IconData pill_outline =
      IconData(0xe8b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pipe_filled' glyph.
  static const IconData pipe_filled =
      IconData(0xe8b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pipe_outline' glyph.
  static const IconData pipe_outline =
      IconData(0xe8b7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'play_filled' glyph.
  static const IconData play_filled =
      IconData(0xe8b8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'play_outline' glyph.
  static const IconData play_outline =
      IconData(0xe8b9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'plus' glyph.
  static const IconData plus =
      IconData(0xe8ba, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'poll_filled' glyph.
  static const IconData poll_filled =
      IconData(0xe8bb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'poll_outline' glyph.
  static const IconData poll_outline =
      IconData(0xe8bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'pregnant' glyph.
  static const IconData pregnant =
      IconData(0xe8bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'presentation_filled' glyph.
  static const IconData presentation_filled =
      IconData(0xe8be, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'presentation_outline' glyph.
  static const IconData presentation_outline =
      IconData(0xe8bf, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'printer_filled' glyph.
  static const IconData printer_filled =
      IconData(0xe8c0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'printer_outline' glyph.
  static const IconData printer_outline =
      IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'qr_code' glyph.
  static const IconData qr_code =
      IconData(0xe8c2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'question_mark_filled' glyph.
  static const IconData question_mark_filled =
      IconData(0xe8c3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'question_mark_outline' glyph.
  static const IconData question_mark_outline =
      IconData(0xe8c4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'quote_left' glyph.
  static const IconData quote_left =
      IconData(0xe8c5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'quote_right' glyph.
  static const IconData quote_right =
      IconData(0xe8c6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'redo' glyph.
  static const IconData redo =
      IconData(0xe8c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'road_filled' glyph.
  static const IconData road_filled =
      IconData(0xe8c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'road_outline' glyph.
  static const IconData road_outline =
      IconData(0xe8c9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'rocket' glyph.
  static const IconData rocket =
      IconData(0xe8ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'ruler_filled' glyph.
  static const IconData ruler_filled =
      IconData(0xe8cb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'ruler_outline' glyph.
  static const IconData ruler_outline =
      IconData(0xe8cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shield_filled' glyph.
  static const IconData shield_filled =
      IconData(0xe8cd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'shield_outline' glyph.
  static const IconData shield_outline =
      IconData(0xe8ce, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sign_language' glyph.
  static const IconData sign_language =
      IconData(0xe8cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sign_out' glyph.
  static const IconData sign_out =
      IconData(0xe8d0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sixty_plus' glyph.
  static const IconData sixty_plus =
      IconData(0xe8d1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sort' glyph.
  static const IconData sort =
      IconData(0xe8d2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star_filled' glyph.
  static const IconData star_filled =
      IconData(0xe8d3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'star_outline' glyph.
  static const IconData star_outline =
      IconData(0xe8d4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stethoscope_filled' glyph.
  static const IconData stethoscope_filled =
      IconData(0xe8d5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stethoscope_outline' glyph.
  static const IconData stethoscope_outline =
      IconData(0xe8d6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stop_filled' glyph.
  static const IconData stop_filled =
      IconData(0xe8d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'stop_outline' glyph.
  static const IconData stop_outline =
      IconData(0xe8d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'strikethrough' glyph.
  static const IconData strikethrough =
      IconData(0xe8d9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'sync' glyph.
  static const IconData sync =
      IconData(0xe8da, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'teddy_bear' glyph.
  static const IconData teddy_bear =
      IconData(0xe8db, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thermometer_filled' glyph.
  static const IconData thermometer_filled =
      IconData(0xe8dc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'thermometer_outline' glyph.
  static const IconData thermometer_outline =
      IconData(0xe8dd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'timer_filled' glyph.
  static const IconData timer_filled =
      IconData(0xe8de, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'timer_outlined' glyph.
  static const IconData timer_outlined =
      IconData(0xe8df, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'times_default' glyph.
  static const IconData times_default =
      IconData(0xe8e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'times_filled' glyph.
  static const IconData times_filled =
      IconData(0xe8e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'times_outline' glyph.
  static const IconData times_outline =
      IconData(0xe8e2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'tooth_filled' glyph.
  static const IconData tooth_filled =
      IconData(0xe8e3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'tooth_outline' glyph.
  static const IconData tooth_outline =
      IconData(0xe8e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'trash_filled' glyph.
  static const IconData trash_filled =
      IconData(0xe8e5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'trash_outline' glyph.
  static const IconData trash_outline =
      IconData(0xe8e6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'underline' glyph.
  static const IconData underline =
      IconData(0xe8e7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'undo' glyph.
  static const IconData undo =
      IconData(0xe8e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'universal_access' glyph.
  static const IconData universal_access =
      IconData(0xe8e9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'upload' glyph.
  static const IconData upload =
      IconData(0xe8ea, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_ban' glyph.
  static const IconData user_ban =
      IconData(0xe8eb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_card' glyph.
  static const IconData user_card =
      IconData(0xe8ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_check' glyph.
  static const IconData user_check =
      IconData(0xe8ed, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_filled' glyph.
  static const IconData user_filled =
      IconData(0xe8ee, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_outline' glyph.
  static const IconData user_outline =
      IconData(0xe8ef, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_return' glyph.
  static const IconData user_return =
      IconData(0xe8f0, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_search' glyph.
  static const IconData user_search =
      IconData(0xe8f1, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_times' glyph.
  static const IconData user_times =
      IconData(0xe8f2, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'user_warning' glyph.
  static const IconData user_warning =
      IconData(0xe8f3, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'video_filled' glyph.
  static const IconData video_filled =
      IconData(0xe8f4, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'video_outline' glyph.
  static const IconData video_outline =
      IconData(0xe8f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'volume_filled' glyph.
  static const IconData volume_filled =
      IconData(0xe8f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'volume_mute_filled' glyph.
  static const IconData volume_mute_filled =
      IconData(0xe8f7, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'volume_mute_outline' glyph.
  static const IconData volume_mute_outline =
      IconData(0xe8f8, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'volume_outline' glyph.
  static const IconData volume_outline =
      IconData(0xe8f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'walker' glyph.
  static const IconData walker =
      IconData(0xe8fa, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'wheelchair' glyph.
  static const IconData wheelchair =
      IconData(0xe8fb, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'wifi' glyph.
  static const IconData wifi =
      IconData(0xe8fc, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'xp' glyph.
  static const IconData xp =
      IconData(0xe8fd, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_minus_filled' glyph.
  static const IconData zoom_minus_filled =
      IconData(0xe8fe, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_minus_outline' glyph.
  static const IconData zoom_minus_outline =
      IconData(0xe8ff, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_outline' glyph.
  static const IconData zoom_outline =
      IconData(0xe900, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_plus_filled' glyph.
  static const IconData zoom_plus_filled =
      IconData(0xe901, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  /// Icon data for 'zoom_plus_outline' glyph.
  static const IconData zoom_plus_outline =
      IconData(0xe902, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
